apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm-charts.rm3l.org
    chart: adguard-home
    targetRevision: 0.24.0
    helm:
      values: |
        services:
          http:
            type: LoadBalancer
            port: 8080
            annotations:
              svc_instance: "adguard-ui"
          dns:
            enabled: true
            type: LoadBalancer
            annotations:
              svc_instance: "adguard-dns"
            externalTrafficPolicy: Local
            tcp:
              port: 53
            udp:
              port: 53
          https:
            enabled: false
          dnsOverTls:
            enabled: false
          dnsOverQuic:
            enabled: false
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
          hosts:
            - host: adguard.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
        persistence:
          config:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
