apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: surfreporter
  namespace: argocd
spec:
  project: default
  source:
    # This is your source of truth
    repoURL: https://github.com/S-McCauley/surf-reporter.git
    targetRevision: main
    path: .
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    # This is where the app will land
    namespace: surfreporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
