apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/S-McCauley/homebase.git
    targetRevision: master
    path: charts   
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
      - CreateNamespace=true
